# permissions for end users to edit simulations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cargo-command
    app.kubernetes.io/managed-by: kustomize
  name: simulation-editor-role
rules:
- apiGroups:
  - simulation.cargo-command.com
  resources:
  - simulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simulation.cargo-command.com
  resources:
  - simulations/status
  verbs:
  - get
